# wranger.toml
name = "ramhacks-25-s"
compatibility_date = "2025-04-10" # Update to the current date
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages
main = "./dist/server.js"
assets = { directory = "./build/client", exclude = ["**/*.map"] }

# Optional: Enable observability
observability = { enabled = true }

# Functions directory (if applicable)
# functions = "./functions"

# Development settings
[dev]
port = 3000
local_protocol = "http"

